//
// Created by SinnyLang on 2025/9/20.
//

#ifndef ANDROIDJUCEDSPINTERFACE_FUNCTIONRESULT_H
#define ANDROIDJUCEDSPINTERFACE_FUNCTIONRESULT_H

#define FUNCTION_RESULT     int
#define FUNCTION_SUCCESS    0
#define FUNCTION_FAILED    -1

#endif //ANDROIDJUCEDSPINTERFACE_FUNCTIONRESULT_H
